# ==================== debezium.properties ====================
# Debezium Engine 基本配置
name=debezium-dameng-connector
connector.class=org.devlive.connector.dameng.DamengConnector

# Offset 存储配置
offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
offset.storage.file.filename=offsets.dat
offset.flush.interval.ms=60000
kafka.topic.name=data-sync-to-dameng\\.(base_server|jyfw_cloud|ent_basic_data|jyfw_business_record|jyfw_ops)\\..*

# dameng 数据库连接信息
database.hostname=192.168.1.69
database.port=5236
database.user=THELING
database.password=OnPCz12u^@~*ecfmZvR
database.dbname=THELING
database.server.name=my-dameng-connector-1999999
database.server.id=8876523423
database.history=io.debezium.relational.history.FileDatabaseHistory
database.history.file.filename=history.dat
database.serverTimezone=UTC
database.connection.adapter=LogMiner
column.propagate.source.type=true

# Schema 和表过滤
schema.include.list=THELING
table.include.list=THELING.*

debezium.log.mining.strategy=online_catalog
debezium.log.mining.continuous.mine=true
debezium.log.level=DEBUG
debezium.source.log.mining.batch.size=1000
debezium.source.poll.interval.ms=1000
debezium.source.transaction.auto.commit.timeout.ms=2000


# 快照模式配置
# initial: 首次启动时对表进行快照
# schema_only: 只捕获 schema，不捕获数据
# never: 不进行快照，只捕获变更
snapshot.mode=schema_only

database.history.kafka.bootstrap.servers=192.168.1.95:9092
database.history.kafka.topic=debezium-history

## 时间配置
decimal.handling.mode=string
time.precision.mode=adaptive